### ISSUE TITLE
Add compile options and locals

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-cli#1]
`renderFile(filename, options, locals)`

Add all the options.

**Comment by tunnckoCore** [comment]
you mean `compileFile`? yea, plus options for `renderFile`

**Comment by RobLoach** [comment]
No, I mean renderFile... It currently just takes filename, we need to add both compile options, and the locals.

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer-cli/pull/10
