### ISSUE TITLE
need check for existance

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-cli#5]
need to check that render\* method exist in the current transformer.
if compile exist then render also will, but if render exist there's no guarantee that compile exist.

[maybe somewhere here](https://github.com/jstransformers/jstransformer-cli/blob/master/index.js#L19-L21), somthing like

``` js
if (typeof transformer.renderFile === 'function')
```

**Comment by ForbesLindesay** [comment]
If you look at jstransformer it already has the checks internally and throws appropriate error messages whenever you try and call a method that doesn't exist.

**Comment by tunnckoCore** [comment]
yea I remember when today was walking down the street.
