### ISSUE TITLE
need tests case for specifing transformer version?

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-cli#6]
i think `lazy-require` support this and we should test it, plus have it in examples and docs in future.

**Comment by ForbesLindesay** [comment]
Personally I'm not convinced using `lazy-require` is the best approach here.  I think it would be better to `require` the jstransformer relative to the file that is being transformed.  i.e. `jstransformer-cli` should be installed globally (or locally for use within npm scripts) but each individual `jstransformer-<whatever>` should be installed locally, and appropriately specified in package.json.

It is then of course up to us to make sure we provide excellent error messages that tell people to just do `jstransformer install <whatever>`.

**Comment by RobLoach** [comment]
> I think it would be better to require the jstransformer relative to the file that is being transformed. i.e. jstransformer-cli should be installed globally (or locally for use within npm scripts) but each individual jstransformer-<whatever> should be installed locally, and appropriately specified in package.json.

That is the current workflow outlined in [the README](https://github.com/jstransformers/jstransformer-cli#jstransformer-cli). `lazy-require` just handles running `npm install jstransformer-<whatever>` if it isn't already available. We could remove for now, however; Re-evaluate it in a later release.

> `jstransformer install <whatever>`

Would this just be an alias to `npm install jstransformer-<whatever> --save` ?

**Comment by tunnckoCore** [comment]
> Would this just be an alias to npm install jstransformer-<whatever> --save ?

yea, he said it.

**Comment by ForbesLindesay** [comment]
I think it would be, but it might be possible that we end up wanting to handle existence/non-existence of package.json files slightly differently.  We need to keep in mind that our users may have virtually no experience with node.js

**Comment by RobLoach** [comment]
Install command: https://github.com/jstransformers/jstransformer-cli/issues/7
Remove lazy-require: https://github.com/jstransformers/jstransformer-cli/issues/8

As for `lazy-require` being able to specify which verison to use: [Add version support](/bevry/lazy-require/issues/1).

**Comment by tunnckoCore** [comment]
actually, seems there lazy-require have support for this [see that comment](https://github.com/jstransformers/jstransformer/issues/13#issuecomment-92390415)
