### ISSUE TITLE
Steam in via .render()

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-cli#9]
```
cat "myfile.jade" > jstransformer jade
```

**Comment by TimothyGu** [comment]
err, did you mean `cat myfile.jade | jstransformer jade`?

jade/bin/jade.js might be of great help.

**Comment by RobLoach** [comment]
^^ That.

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer-cli/pull/10
